#!/usr/bin/env python3
"""Build and verify relocatable support bundles using only the Python standard library."""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import sys


REPO = Path(__file__).resolve().parents[1]
GENERATED = '<!-- Generated by scripts/bundle_skills.py; edit skill-dependencies.json or canonical sources. -->'
INDEX = Path('references/dependencies.md')
LOCK = Path('embedded/.bundle.json')
NAME = re.compile(r'^[a-z0-9]+(?:-[a-z0-9]+)*$')
LINK = re.compile(r'(?<!!)\[([^\]\n]+)\]\(([^\s)]+)(?:\s+"[^"]*")?\)')


def digest(data):
    return hashlib.sha256(data).hexdigest()


def read_manifest(repo):
    manifest = json.loads((repo / 'skill-dependencies.json').read_text())
    if manifest.get('version') != 1:
        raise ValueError('Unsupported dependency manifest version')
    modules = manifest['modules']
    for name, module in modules.items():
        if not NAME.fullmatch(name):
            raise ValueError(f'Invalid module name: {name}')
        source = (repo / module['source']).resolve()
        if not source.is_relative_to(repo.resolve()) or source == repo.resolve():
            raise ValueError(f'Module source escapes the repository: {name}')
        entry = Path(module.get('entry', 'SKILL.md'))
        if entry.is_absolute() or '..' in entry.parts or not (source / entry).is_file():
            raise ValueError(f'Missing or unsafe entrypoint: {name}')
        if module['kind'] not in {'owned', 'third-party', 'runtime-guide'}:
            raise ValueError(f'Unknown module kind: {name}')
        if module['kind'] == 'third-party' and not (source / 'LICENSE').is_file():
            raise ValueError(f'Third-party module lacks a license: {name}')
        seen = set()
        for edge in module['dependencies']:
            dep = edge['name']
            if dep not in modules or dep in seen or not edge['when'].strip():
                raise ValueError(f'Invalid dependency in {name}: {dep}')
            seen.add(dep)
    return manifest


def closure(modules, root):
    seen, pending = {root}, [root]
    for name in pending:
        for edge in modules[name]['dependencies']:
            if edge['name'] not in seen:
                seen.add(edge['name'])
                pending.append(edge['name'])
    return sorted(seen - {root})


def source_files(repo, module):
    source = repo / module['source']
    for path in sorted(source.rglob('*')):
        relative = path.relative_to(source)
        if any(p in {'embedded', 'agents', '__pycache__', '.git'} for p in relative.parts):
            continue
        if relative == INDEX or path.name == '.DS_Store':
            continue
        if path.is_symlink():
            raise ValueError(f'Bundle sources must be real files: {path}')
        if path.is_file():
            yield relative, path


def destination(root_name, name, relative, modules):
    relative = Path(relative)
    if name == root_name:
        return relative
    if relative == Path(modules[name].get('entry', 'SKILL.md')):
        relative = Path('GUIDE.md')
    return Path('embedded') / name / relative


def relative_link(from_file, to_file):
    return Path(os.path.relpath(to_file, from_file.parent)).as_posix()


def rewrite_links(text, source_file, output_file, repo, modules, root_name, included):
    """Translate source and already-bundled Markdown links into one flat bundle."""
    sources = [(name, (repo / m['source']).resolve()) for name, m in modules.items()]

    def replace(match):
        label, url = match.groups()
        if re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', url) or url.startswith(('#', '/')):
            return match.group(0)
        raw, separator, fragment = url.partition('#')
        target = (source_file.parent / raw).resolve()
        for name, source in sources:
            if not target.is_relative_to(source):
                continue
            rel = target.relative_to(source)
            if len(rel.parts) >= 3 and rel.parts[0] == 'embedded':
                name, rel = rel.parts[1], Path(*rel.parts[2:])
                if name in modules and rel == Path('GUIDE.md'):
                    rel = Path(modules[name].get('entry', 'SKILL.md'))
            if name not in included:
                raise ValueError(f'Undeclared dependency {name}: {source_file}')
            link = relative_link(output_file, destination(root_name, name, rel, modules))
            if separator:
                link += '#' + fragment
            return f'[{label}]({link})'
        return match.group(0)

    return LINK.sub(replace, text)


def dependency_index(modules, root_name, name, included):
    output_file = destination(root_name, name, INDEX, modules)
    rows = [GENERATED, '# Bundled support', '',
            'This package includes the support below. Read only the guidance required by the current task. '
            'A dependency is available guidance, not an instruction to run every workflow, install packages, '
            'spawn agents, or expand authorization. User direction and the project contract remain authoritative.', '',
            'Resolve named supporting skills through these local links before looking for a separate installation. '
            'Resolve scripts and assets relative to the supporting guide, not the calling skill. Reuse guidance '
            'already read; cross-references between domain owners must not cause a recursive review loop.', '']
    if modules[name]['dependencies']:
        rows += ['| Support | Read when |', '|---|---|']
        for edge in modules[name]['dependencies']:
            dep = edge['name']
            path = destination(root_name, dep, modules[dep].get('entry', 'SKILL.md'), modules)
            rows.append(f'| [{dep}]({relative_link(output_file, path)}) | {edge["when"]} |')
    else:
        rows.append('This support guide has no additional skill dependencies.')
    other = sorted(included - {name} - {e['name'] for e in modules[name]['dependencies']})
    if other:
        rows += ['', 'Other support already present in this package (load only if an applicable guide refers to it):', '']
        rows.append(', '.join(f'[{dep}]({relative_link(output_file, destination(root_name, dep, modules[dep].get("entry", "SKILL.md"), modules))})' for dep in other) + '.')
    rows += ['', 'Browser sessions, image-generation tools, project packages, credentials, and current provider '
             'documentation are runtime capabilities. They are not supplied or authorized by this bundle. '
             'Follow the active environment\'s tool instructions and report unavailable capabilities honestly.', '']
    return '\n'.join(rows).encode()


def expected_bundle(repo, manifest, root_name):
    modules = manifest['modules']
    dependencies = closure(modules, root_name)
    if not dependencies:
        return {}
    included = set(dependencies) | {root_name}
    outputs = {INDEX: dependency_index(modules, root_name, root_name, included)}
    source_hashes = {}
    for name in dependencies:
        module = modules[name]
        source_hashes[name] = {}
        for relative, source in source_files(repo, module):
            data = source.read_bytes()
            source_hashes[name][relative.as_posix()] = digest(data)
            output = destination(root_name, name, relative, modules)
            if source.suffix == '.md':
                text = rewrite_links(data.decode(), source, output, repo, modules, root_name, included)
                if relative == Path(module.get('entry', 'SKILL.md')):
                    text = re.sub(r'\A---\n.*?\n---\n', '', text, count=1, flags=re.S)
                    text = ('> Bundled supporting guide. Preserve the calling workflow\'s scope and project authority. '
                            'Use [local support](references/dependencies.md) for named dependencies; this guide does not '
                            'grant additional tool or mutation permissions.\n\n') + text
                data = text.encode()
            outputs[output] = data
        outputs[destination(root_name, name, INDEX, modules)] = dependency_index(modules, root_name, name, included)
    third_party = {name: record for name, record in json.loads((repo / 'vendor/sources.json').read_text()).items() if name in included} if (repo / 'vendor/sources.json').exists() else {}
    if third_party:
        outputs[Path('embedded/SOURCES.json')] = (json.dumps(third_party, ensure_ascii=False, indent=2) + '\n').encode()
    metadata = {'version': 1, 'root': root_name, 'modules': dependencies, 'source_sha256': source_hashes,
                'files': {p.as_posix(): digest(b) for p, b in sorted(outputs.items())}}
    outputs[LOCK] = (json.dumps(metadata, ensure_ascii=False, indent=2) + '\n').encode()
    return outputs


def safe_managed_path(root, relative):
    path = Path(relative)
    if path.is_absolute() or '..' in path.parts or not (path == INDEX or path.parts[:1] == ('embedded',)):
        raise ValueError(f'Unsafe generated path: {relative}')
    target = root / path
    if not target.resolve().is_relative_to(root.resolve()):
        raise ValueError(f'Generated path escapes the skill: {relative}')
    return target


def synchronize(root, expected, check):
    old = {}
    if (root / LOCK).exists():
        old = json.loads((root / LOCK).read_text())['files']
        old[LOCK.as_posix()] = digest((root / LOCK).read_bytes())
    elif (root / 'embedded').exists():
        raise ValueError(f'Refusing an unmanaged embedded directory: {root}')
    for relative, previous_digest in old.items():
        path = safe_managed_path(root, relative)
        if path.exists() and digest(path.read_bytes()) != previous_digest:
            raise ValueError(f'Generated file was edited; preserve it and update its canonical source: {path}')
    expected_names = {p.as_posix() for p in expected}
    actual_names = {p.relative_to(root).as_posix() for p in (root / 'embedded').rglob('*') if p.is_file()}
    unexpected = actual_names - set(old) - expected_names
    if unexpected:
        raise ValueError(f'Unmanaged files in bundle: {root}: {sorted(unexpected)}')
    changed = [p for p, data in expected.items() if not (root / p).is_file() or (root / p).read_bytes() != data]
    stale = [Path(p) for p in old if p not in expected_names]
    if check:
        if changed or stale:
            raise ValueError(f'Outdated bundle: {root.name}; changed={len(changed)}, stale={len(stale)}')
        return
    for relative in changed:
        path = safe_managed_path(root, relative)
        if path.exists() and relative.as_posix() not in old:
            raise ValueError(f'Refusing to overwrite an unmanaged file: {path}')
    for relative in changed:
        path = safe_managed_path(root, relative)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(expected[relative])
    for relative in stale:
        path = safe_managed_path(root, relative)
        path.unlink(missing_ok=True)
    # Remove only empty directories left by the previous managed snapshot.
    for path in sorted((root / 'embedded').rglob('*'), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def check_links(root):
    errors = []
    for file in sorted(root.rglob('*.md')):
        if 'assets' in file.relative_to(root).parts:
            continue
        text = re.sub(r'^```[^\n]*\n.*?^```[^\n]*$', '', file.read_text(), flags=re.M | re.S)
        for _, url in LINK.findall(text):
            if re.match(r'^[a-zA-Z][a-zA-Z0-9+.-]*:', url) or url.startswith('#'):
                continue
            target = (file.parent / url.split('#')[0]).resolve()
            if not target.is_relative_to(root.resolve()) or not target.exists():
                errors.append(f'{file.relative_to(root)} -> {url}')
    if errors:
        raise ValueError(f'Nonportable or broken links in {root.name}:\n' + '\n'.join(errors))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('command', choices=['build', 'check'])
    parser.add_argument('--root', type=Path, default=REPO)
    parser.add_argument('--skill', action='append', help='Limit to named owned skills; repeatable')
    args = parser.parse_args()
    repo = args.root.resolve()
    manifest = read_manifest(repo)
    roots = args.skill or [n for n, m in manifest['modules'].items() if m['kind'] == 'owned']
    for name in roots:
        module = manifest['modules'].get(name)
        if not module or module['kind'] != 'owned':
            raise ValueError(f'Not an owned skill: {name}')
        root = repo / module['source']
        expected = expected_bundle(repo, manifest, name)
        synchronize(root, expected, check=args.command == 'check')
        check_links(root)
        print(f'{name}: {len(closure(manifest["modules"], name))} bundled support modules; links OK')


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, KeyError) as error:
        print(f'bundle-skills: {error}', file=sys.stderr)
        sys.exit(1)
